version: '3'
services:
  mydb:
    image: postgres:12
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: userOne
 
volumes:
  db-data:
    driver: local